### ISSUE TITLE
onnx model with or without the init_flow as input arg

### ISSUE THREAD

**Issue by deephog** [ibaiGorordo/CREStereo-Pytorch#5] opened 2022-04-20 21:48 UTC
Thank you for your excellent work! After reading your code and how you converted the model to onnx, I came up with the following confusion.

In your pytorch code, the model deals with the init_flow very differently depending on whether or not you provide it, how could you manage to wrap it into a onnx model with an example input that always contain an init_flow? That means you need to always provide an init_flow (if it is the initial run, then the init_flow should be all zeros?), but does it change how the model works? 

Thanks!

**Comment by deephog** [comment] 2022-04-20 23:14
Not sure if I understand the issue correctly, but after reading your repo and PINTO0309's back and forth, I may have figured out how you guys eventually made the model work. Please correct me if I'm wrong:

1. You need to convert the model twice, once without the init_flow and once with the init_flow. (So the commented out part in your [script](https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/convert_to_onnx.py)) are not options, but two separate runs.
2. Then use the [merging tool](https://github.com/PINTO0309/PINTO_model_zoo/blob/main/284_CREStereo/onnx_merge.py) PINTO0309 developed to merge the two parts into one. Or, just use them separately in sequence.

**Comment by PINTO0309** [comment] 2022-04-21 11:14
>You need to convert the model twice, once without the init_flow and once with the init_flow. So the commented out part in your [script](https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/convert_to_onnx.py) are not options, but two separate runs.
Then use the [merging tool](https://github.com/PINTO0309/PINTO_model_zoo/blob/main/284_CREStereo/onnx_merge.py) PINTO0309 developed to merge the two parts into one. Or, just use them separately in sequence.

That is correct. However, it has been confirmed that sufficient performance can be obtained even when the model in `*_init_*.onnx` is used by itself without bothering to combine models.

**Comment by deephog** [comment] 2022-04-21 16:16
> > You need to convert the model twice, once without the init_flow and once with the init_flow. So the commented out part in your [script](https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/convert_to_onnx.py) are not options, but two separate runs.
> > Then use the [merging tool](https://github.com/PINTO0309/PINTO_model_zoo/blob/main/284_CREStereo/onnx_merge.py) PINTO0309 developed to merge the two parts into one. Or, just use them separately in sequence.
> 
> That is correct. However, it has been confirmed that sufficient performance can be obtained even when the model in `*_init_*.onnx` is used by itself without bothering to combine models. ![image](https://user-images.githubusercontent.com/33194443/164447213-b33a4f88-c049-489a-b64d-fccec6e051b6.png)

Thanks a lot! I may try to convert the models to tensorrt today

**Comment by deephog** [comment] 2022-04-21 20:40
@PINTO0309 I successfully exported a TR engine with the init_flow, but failed without the init_flow. The one without the init_flow is the first round, so basically I failed to generate a usable TR engine. 

I tried exporting TR model with onnx files that you exported, but same error was encountered:

04/21/2022-15:30:35] [TRT] [V] init_Reciprocal_443 [Reciprocal] outputs: [init_onnx::Einsum_588 -> (1, 880, 8)[FLOAT]], 
[04/21/2022-15:30:35] [TRT] [V] Parsing node: init_Einsum_444 [Einsum]
[04/21/2022-15:30:35] [TRT] [V] Searching for input: init_Q
[04/21/2022-15:30:35] [TRT] [V] Searching for input: init_KV
[04/21/2022-15:30:35] [TRT] [V] Searching for input: init_onnx::Einsum_588
[04/21/2022-15:30:35] [TRT] [V] init_Einsum_444 [Einsum] inputs: [init_Q -> (1, 880, 8, 32)[FLOAT]], [init_KV -> (1, 8, 32, 32)[FLOAT]], [init_onnx::Einsum_588 -> (1, 880, 8)[FLOAT]], 
[04/21/2022-15:30:36] [TRT] [E] [layers.cpp::EinsumLayer::5821] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/layers.cpp::EinsumLayer::5821, condition: nbInputs > 0 && nbInputs <= MAX_EINSUM_NB_INPUTS

Do you have any idea of how to solve this problem?

**Comment by deephog** [comment] 2022-04-21 21:39
@PINTO0309 it seems like tensorrt does not support einsum with more than 2 input tensors?

**Comment by deephog** [comment] 2022-04-21 23:16
I think I figured out.

In "nets -> attention -> linear_attention.py", line 45:

I decomposed:

queried_values = torch.einsum("nlhd,nhdv,nlh->nlhv", Q, KV, Z) * v_length

into:

T = torch.einsum("nlhd,nhdv->nlhv", Q, KV)
queried_values = torch.einsum("nlhv,nlh->nlhv", T, Z) * v_length

and the error messages are gone, RT engine successfully compiled.

**Comment by PINTO0309** [comment] 2022-04-21 23:17
TRT conversion succeeds without doing anything special.
```bash
docker run --gpus all -it --rm \
-v `pwd`:/home/user/workdir \
ghcr.io/pinto0309/openvino2tensorflow:latest

python
```
```python
>>> import onnxruntime
>>> import os
>>> onnx_session = onnxruntime.InferenceSession(
...     model_path,
...     sess_options=session_option,
...     providers=[
...         (
...             'TensorrtExecutionProvider', {
...                 'trt_engine_cache_enable': True,
...                 'trt_engine_cache_path': os.path.dirname(model_path),
...                 'trt_fp16_enable': True,
...             }
...         ),
...     ],
... )
```
```bash
2022-04-21 22:41:40.821657980 [W:onnxruntime:Default, tensorrt_execution_provider.h:59 log] [2022-04-21 22:41:40 WARNING] external/onnx-tensorrt/onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
2022-04-21 22:41:41.344680966 [E:onnxruntime:Default, tensorrt_execution_provider.h:57 log] [2022-04-21 22:41:41   ERROR] [layers.cpp::EinsumLayer::5525] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/layers.cpp::EinsumLayer::5525, condition: nbInputs > 0 && nbInputs <= MAX_EINSUM_NB_INPUTS)
2022-04-21 22:41:41.435552432 [E:onnxruntime:Default, tensorrt_execution_provider.h:57 log] [2022-04-21 22:41:41   ERROR] [layers.cpp::EinsumLayer::5525] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/layers.cpp::EinsumLayer::5525, condition: nbInputs > 0 && nbInputs <= MAX_EINSUM_NB_INPUTS)
2022-04-21 22:41:41.488666314 [E:onnxruntime:Default, tensorrt_execution_provider.h:57 log] [2022-04-21 22:41:41   ERROR] [layers.cpp::EinsumLayer::5525] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/layers.cpp::EinsumLayer::5525, condition: nbInputs > 0 && nbInputs <= MAX_EINSUM_NB_INPUTS)
2022-04-21 22:41:41.545094305 [E:onnxruntime:Default, tensorrt_execution_provider.h:57 log] [2022-04-21 22:41:41   ERROR] [layers.cpp::EinsumLayer::5525] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/layers.cpp::EinsumLayer::5525, condition: nbInputs > 0 && nbInputs <= MAX_EINSUM_NB_INPUTS)
2022-04-21 22:41:44.036382351 [W:onnxruntime:Default, tensorrt_execution_provider.h:59 log] [2022-04-21 22:41:44 WARNING] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.6.1
2022-04-21 22:44:22.038848801 [W:onnxruntime:Default, tensorrt_execution_provider.h:59 log] [2022-04-21 22:44:22 WARNING] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.6.1
2022-04-21 22:44:22.058828280 [W:onnxruntime:Default, tensorrt_execution_provider.h:59 log] [2022-04-21 22:44:22 WARNING] TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.6.1
```
![image](https://user-images.githubusercontent.com/33194443/164566347-11df16fb-a71f-4a03-8c90-913ed9cf9381.png)

**Comment by PINTO0309** [comment] 2022-04-21 23:31
@deephog 

>I decomposed:
queried_values = torch.einsum("nlhd,nhdv,nlh->nlhv", Q, KV, Z) * v_length

>into:
T = torch.einsum("nlhd,nhdv->nlhv", Q, KV)
queried_values = torch.einsum("nlhv,nlh->nlhv", T, Z) * v_length

This workaround would be great if the output results would match. I would like to know if the outputs match.

**Comment by deephog** [comment] 2022-04-21 23:31
@PINTO0309 I believe you are using TensorRT 8.2 right? I tried your docker image, still got the same error code. And there was another guy posted the same issue I believe, maybe in another repo of @ibaiGorordo 's, just couldn't find it at the moment.

If you really didn't see any error message, then I should really try your method in the future. So maybe the trt engine compiler included in the onnxruntime package has better compatibility?

**Comment by PINTO0309** [comment] 2022-04-21 23:33
There is in fact an error. It is shown in the middle of the log. However, the TensorRT Provider in onnxruntime seems to ignore the error and continue the conversion.

**Comment by deephog** [comment] 2022-04-22 00:00
> @deephog
> 
> > I decomposed:
> > queried_values = torch.einsum("nlhd,nhdv,nlh->nlhv", Q, KV, Z) * v_length
> 
> > into:
> > T = torch.einsum("nlhd,nhdv->nlhv", Q, KV)
> > queried_values = torch.einsum("nlhv,nlh->nlhv", T, Z) * v_length
> 
> This workaround would be great if the output results would match. I would like to know if the outputs match.

Sorry I missed this one. The outputs are exactly the same. It is similar to converting a + b + c into d = a + b, then d + c

**Comment by PINTO0309** [comment] 2022-04-22 00:02
Excellent. I am going to reconvert the model and recommit to the zoo.

**Comment by ibaiGorordo** [comment] 2022-04-22 11:20
> @PINTO0309 I believe you are using TensorRT 8.2 right? I tried your docker image, still got the same error code. And there was another guy posted the same issue I believe, maybe in another repo of @ibaiGorordo 's, just couldn't find it at the moment.
> 
> If you really didn't see any error message, then I should really try your method in the future. So maybe the trt engine compiler included in the onnxruntime package has better compatibility?

Just for future reference, here is the mentioned issue: https://github.com/ibaiGorordo/ONNX-CREStereo-Depth-Estimation/issues/1

Nice to see that you found the solution.

**Comment by PINTO0309** [comment] 2022-04-22 23:39
After applying deephog's workaround, we succeeded in converting it completely to TensorRT. I have therefore optimized and re-committed all of the zoo's ONNX models.

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/284_CREStereo
![image](https://user-images.githubusercontent.com/33194443/164817275-c654bd0f-d902-45ce-9d4b-b6e9a0a7a822.png)

**Closed** 2022-04-26 12:49 UTC

**Comment by ashank-art** [comment] 2023-10-25 08:25
Hi, regarding the pytorch model conversion to

> > > You need to convert the model twice, once without the init_flow and once with the init_flow. So the commented out part in your [script](https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/convert_to_onnx.py) are not options, but two separate runs.
> > > Then use the [merging tool](https://github.com/PINTO0309/PINTO_model_zoo/blob/main/284_CREStereo/onnx_merge.py) PINTO0309 developed to merge the two parts into one. Or, just use them separately in sequence.
> > 
> > 
> > That is correct. However, it has been confirmed that sufficient performance can be obtained even when the model in `*_init_*.onnx` is used by itself without bothering to combine models. ![image](https://user-images.githubusercontent.com/33194443/164447213-b33a4f88-c049-489a-b64d-fccec6e051b6.png)
> 
> Thanks a lot! I may try to convert the models to tensorrt today

Hi, @deephog @ibaiGorordo I tired converting the pytorch model to onnx using the script provided, can u let me know how to generate the init version of the model, is it with the half image resolution or using the full image resolution?

For generating the merged model, we need to combine init and next models, with respect to the resolution for init and next models

Assume for generating the combined model of resolution 480 * 640, we need to merge init model of resolution 480 * 640 and next model with resolution 480 * 640, but what is the input resolution used for generating the init model ?
Is that 480 * 640 or 960 * 1280? Since according to this script (https://github.com/ibaiGorordo/CREStereo-Pytorch/blob/main/convert_to_onnx.py) init model is generated with half of the input resolution.

![Onnx_issue](https://github.com/ibaiGorordo/CREStereo-Pytorch/assets/52282401/e862da1d-6fd1-4715-8e76-fbad71c2e0c5)
