### ISSUE TITLE
RuntimeError: Unsupported: ONNX export of instance_norm for unknown channel size.

### ISSUE THREAD

**Issue by deephog** [ibaiGorordo/CREStereo-Pytorch#7] opened 2022-05-05 00:55 UTC
Hi @ibaiGorordo, wonder if you ever tried to quantize CREStereo. I tried the explicit quantization approach with pytorch_quantization, which automatically substitutes the supported layers with their quant_version, so it will record the statistics when I run the calibration process.

The calibration process was successful, then I get a quantized version of the model and weights. But afterwards, when I try to export the quantized model to ONNX as usual, I encountered the error mentioned in the title. The full error message goes this way:

> /workspace/projects/CREStereo-Pytorch/nets/corr.py:66: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  rights = torch.split(right_feature, right_feature.shape[1]//4, dim=1)
/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:779: UserWarning: ONNX export mode is set to inference mode, but operator instance_norm is set to training  mode. The operators will be exported in training , as specified by the functional operator.
  warnings.warn("ONNX export mode is set to " + training_mode +
Traceback (most recent call last):
  File "model_quant.py", line 225, in <module>
    torch.onnx.export(model_init.cpu(),
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 321, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 134, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 746, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 524, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 243, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 378, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1069, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 1405, in instance_norm
    raise RuntimeError("Unsupported: ONNX export of instance_norm for unknown "
RuntimeError: Unsupported: ONNX export of instance_norm for unknown channel size.

It could be because of instance_norm being set to training_mode, but I failed to set it to eval mode after trying all the methods I know. I will post it to pytorch forum as well, just see if you have any thoughts on this or not.

**Comment by PINTO0309** [comment] 2022-05-05 02:08
Perhaps just Reshape to the fourth dimension.

**Comment by deephog** [comment] 2022-05-05 05:54
> Perhaps just Reshape to the fourth dimension.

I made a stupid mistake. The manual said I need to put these two lines down for pytorch to export quantized version of layers:

> from pytorch_quantization import nn as quant_nn
quant_nn.TensorQuantizer.use_fb_fake_quant = True


However, after I generated the simplified ONNX file, the engine compiling process still gave me this error:

> [05/05/2022-01:44:01] [TRT] [V] Running: ConstWeightsQuantizeFusion
[05/05/2022-01:44:01] [TRT] [V] ConstWeightsQuantizeFusion: Fusing update_block.gru.convr2.weight with QuantizeLinear_1620_quantize_scale_node
[05/05/2022-01:44:01] [TRT] [V] Running: ConstWeightsQuantizeFusion
[05/05/2022-01:44:01] [TRT] [V] ConstWeightsQuantizeFusion: Fusing update_block.gru.convq2.weight with QuantizeLinear_1629_quantize_scale_node
[05/05/2022-01:44:01] [TRT] [V] Running: ConstWeightsQuantizeFusion
[05/05/2022-01:44:01] [TRT] [V] ConstWeightsQuantizeFusion: Fusing update_block.flow_head.conv1.weight with QuantizeLinear_1641_quantize_scale_node
[05/05/2022-01:44:01] [TRT] [V] Running: ConstWeightsQuantizeFusion
[05/05/2022-01:44:01] [TRT] [V] ConstWeightsQuantizeFusion: Fusing update_block.flow_head.conv2.weight with QuantizeLinear_1648_quantize_scale_node
[05/05/2022-01:44:01] [TRT] [V] Running: VanillaSwapWithFollowingQ
[05/05/2022-01:44:01] [TRT] [V] Swapping Relu_631 with QuantizeLinear_652_quantize_scale_node
[05/05/2022-01:44:01] [TRT] [V] Running: SplitQAcrossPrecedingFanIn
[05/05/2022-01:44:01] [TRT] [V] Running: SplitQAcrossPrecedingFanIn
[05/05/2022-01:44:02] [TRT] [V] Running: SplitQAcrossPrecedingFanIn
[05/05/2022-01:44:02] [TRT] [V] Running: SplitQAcrossPrecedingFanIn
[05/05/2022-01:44:02] [TRT] [V] Running: SplitQAcrossPrecedingFanIn
[05/05/2022-01:44:02] [TRT] [E] 2: [checkSanity.cpp::checkSanity::106] Error Code 2: Internal Error (Assertion regionNames.find(r->name) == regionNames.end() failed. Found duplicate region name onnx::Concat_1406_clone_1)
[05/05/2022-01:44:02] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::619] Error Code 2: Internal Error (Assertion engine != nullptr failed. )

It is about duplicate node name, but as I go through the simplified ONNX model, there is no such duplicated node. Maybe something generated while the compilation of the rt engine.

**Comment by PINTO0309** [comment] 2022-05-05 06:58
I cannot find out what is happening because the onnx file is not shared.

**Comment by deephog** [comment] 2022-05-05 13:08
[ONNX](https://drive.google.com/file/d/1DAF3dYsFO7aN7ZmPoNEdnCRTsKTqTCKm/view) Sorry, i uploaded it to the tensorrt forum but forgot it here

**Comment by deephog** [comment] 2022-05-05 13:41
> I cannot find out what is happening because the onnx file is not shared.

Looks like I was wrong. The duplicated node name is Concat_1406. I thought it is the name of the Concat op, but it turns out to be the name of the input node of the Concat op, actually several Concat nodes, like 4 or 5 Concat ops has this same input node name.

I will try to manually change the node and see what happens. Don't know how it happens, I may look into the ONNX file before the simplifier to see what caused this.

**Comment by deephog** [comment] 2022-05-05 13:51
> I cannot find out what is happening because the onnx file is not shared.

No I was wrong again. They all share the output of the same Concat op, so it is reasonable. I can guess what could happened. This "SplitQAcrossPrecedingFanIn" process may temporarily create duplicate input nodes for optimization purposes, then because so many ops shared the same nodes, they all tried to do the same "split" thing, then it found out that "clone_1" it tries to create is already occupied. 

If it is the case, deep down it should be a bug of TensorRT. But for a temporary workaround, we may try to rename the nodes. But for a node that is shared by many ops, how could you name it differently for each op?

**Comment by PINTO0309** [comment] 2022-05-05 14:03
Since there are no figures, etc., I could not quite understand what "so many ops shared the same nodes" means.

Without understanding, I will just write here what I think of for now. It may be possible to circumvent this by extrapolating a meaningless Multiply or meaningless zero addition OP to the middle portion between the shared nodes.
https://github.com/PINTO0309/sna4onnx
```bash
$ sna4onnx \
--input_onnx_file_path crestereo_init_iter2_120x160.onnx \
--connection_src_op_output_name Sub_451 onnx::Pow_603 dummy_mul inp1 \
--connection_dest_op_input_name dummy_mul out1 Div_458 onnx::Pow_603 \
--add_op_type Mul \
--add_op_name dummy_mul \
--add_op_input_variables inp1 float32 [1,70,256] \
--add_op_input_variables inp2_const float32 [1] \
--add_op_output_variables out1 float32 [1,70,256] \
--output_onnx_file_path test.onnx
```
![image](https://user-images.githubusercontent.com/33194443/166940360-db0a5968-be27-4faf-b4c4-d2bc4b2991cc.png)
![image](https://user-images.githubusercontent.com/33194443/166940388-30ac3e0c-1970-424c-a091-89d5dbfbc8a9.png)

**Comment by deephog** [comment] 2022-05-05 14:08
> Since there are no figures, etc., I could not quite understand what "so many ops shared the same nodes" means.
> 
> Without understanding, I will just write here what I think of for now. It may be possible to circumvent this by extrapolating a meaningless Multiply or meaningless zero addition OP to the middle portion between the shared nodes. https://github.com/PINTO0309/sna4onnx
> 
> ```shell
> $ sna4onnx \
> --input_onnx_file_path crestereo_init_iter2_120x160.onnx \
> --connection_src_op_output_name Sub_451 onnx::Pow_603 dummy_mul inp1 \
> --connection_dest_op_input_name dummy_mul out1 Div_458 onnx::Pow_603 \
> --add_op_type Mul \
> --add_op_name dummy_mul \
> --add_op_input_variables inp1 float32 [1,70,256] \
> --add_op_input_variables inp2_const float32 [1] \
> --add_op_output_variables out1 float32 [1,70,256] \
> --output_onnx_file_path test.onnx
> ```
> 
> ![image](https://user-images.githubusercontent.com/33194443/166940360-db0a5968-be27-4faf-b4c4-d2bc4b2991cc.png) ![image](https://user-images.githubusercontent.com/33194443/166940388-30ac3e0c-1970-424c-a091-89d5dbfbc8a9.png)

Yes this could be the workaround I need, let me try it, thanks!

**Comment by deephog** [comment] 2022-05-05 14:48
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1251361/166950116-726f901f-34bd-4765-84c7-d8f9c6411e99.png">

**Comment by PINTO0309** [comment] 2022-05-05 15:26
One OP(node) of ONNX consists of the following four elements.

1. node.name ... string
2. node.inputs ... `Variable` list or `Constant` list
3. node.outputs ... `Variable` list or `Constant` list
4. node.attr .. attributes, numpy values

However, `2. node.inputs` does not exist in the `Constant` OP. The official ONNX documentation describes what attributes, input and output, are available for the OP you wish to manipulate. Constants are defined by a single operation, `Constant` OP. 
https://github.com/onnx/onnx/blob/main/docs/Operators.md

`Variable` is only a variable and must be passed as an input, either the output of some OP or a constant. In other words, input variable is nothing more than a reference to the output information of another OP. The idea is the same as Python's object references.

The `Variable` must also have a `name`, `value type` and `shape`. Here, `shape` is not a constant, but specifies the output shape of the other OPs to be connected.

```
                            shape                           shape                                shape
{A op} output_variable [1,3, 122,122] -> input_variable [1,3, 122,122] {B op} output_variable1 [224,224]
                                                                              output_variable2 [1,1]
```

Instead of challenging yourself with a complex model first, it is better to start with a sample model and sample commands committed to the repository to get a better understanding. The concepts are not very difficult.

**Comment by deephog** [comment] 2022-05-05 15:37
Yes, I fully understand what you described. But the problem is, maybe the screenshot was not clear, I'm adding a dummy_mul between two 'Concat' ops, and to initialize the input (the one connecting to the source Concat) of the dummy_mul, I need to specify its shape, as you said, but the precedent op (Concat) does not have a specified shape as its attribute. In this case, does sna4onnx accept any kind of "dummy shape"?

**Comment by PINTO0309** [comment] 2022-05-05 15:46
>I need to specify its shape, as you said, but the precedent op (Concat) does not have a specified shape as its attribute.

That's right. Look closely at the structure of the model. You need to check the part before Concat. 
Here,
![image](https://user-images.githubusercontent.com/33194443/166960804-969c4c09-0bca-4ec8-9628-15e4a9bed718.png)

In particular, at the Concat on the right branch, the model only computes a 180x320 fixed geometry. I would try to replace the right-hand branch calculation with a fixed value. I would either modify the PyTorch logic or use sne4onnx to isolate the model, although it would be quite a hassle.
https://github.com/PINTO0309/sne4onnx

However, just like debugging a program, it is always a good idea to split the model and check the geometry in order to isolate the problem areas.

**Closed** 2022-07-25 20:32 UTC

**Comment by ynma-hanvo** [comment] 2023-11-29 09:01
@deephog  thansk for sharing your work .  I am interested at the final outcome.  did you successfully compiled the onnx into tensorrt and what about the perforamnce

**Comment by ynma-hanvo** [comment] 2024-01-31 08:29
I also got the same istance_norm  error message when exporting the quantization model.   the issue is pytorch jit trace bug I guess , as I was able to run the quantization model but not export.  but  how to fix it
